<?php

/**
* Implements hook_menu().
*/
function custom_linkedIn_menu(){
    $items['linkedin/login'] = array(
        'type' => MENU_CALLBACK,
        'description' => 'Login with Linked In',
        'page callback' => 'linkedin_get_token_request',
        'page arguments' => array('login'),
        'access callback' => True,
    );
    $items['linkedin/register'] = array(
        'type' => MENU_CALLBACK,
        'description' => 'Login with Linked In',
        'page callback' => 'linkedin_get_token_request',
        'page arguments' => array('register'),
        'access callback' => True,
    );
    $items['linkedin/%/connect'] = array(
        'type' => MENU_CALLBACK,
        'description' => 'Login with Linked In',
        'page callback' => 'linkedin_get_token_request',
        'page arguments' => array('connect'),
        'access callback' => 'connect_access',
        'access arguments' => array(1),
    );

    $items['linkedin/login/finalize'] = array(
        'title' => t('LinkedIn Login'),
        'description' => t('LinkedIn Login function'),
        'page callback' => 'linked_in_login',
        'access arguments' => array('access content'),
        'type' => MENU_CALLBACK,
    );
    $items['linkedin/register/finalize'] = array(
        'title' => t('LinkedIn Register'),
        'description' => t('LinkedIn Register function'),
        'page callback' => 'linked_in_register',
        'access arguments' => array('access content'),
        'type' => MENU_CALLBACK,
    );
    $items['linkedin/connect/finalize'] = array(
        'title' => t('LinkedIn connection'),
        'description' => t('LinkedIn Connection function'),
        'page callback' => 'linked_in_connect',
        'access arguments' => array('access content'),
        'type' => MENU_CALLBACK,
    );

    //LinkedIn profile tab for users
    $items['user/%/linkedin'] = array(
        'title' => 'Linkedin',
        'type' => MENU_LOCAL_TASK,
        'description' => 'LinkedIn profile data',
        'page callback' => 'linked_in_profile',
        'page arguments' => array(1),
        'access callback' => 'has_linkedin_account',
        'access arguments' => array(1),
    );

    return $items;
}

/**
 * Implements hook_theme().
 */
function custom_linkedIn_theme(){
    $return = array();

    $return['custom_linkedIn_user_page'] = array(
        'variables' => array('profile' => Null),
        'template' => 'custom-linkedIn-user-page',
    );

    return $return;
}

/**
 * Implements hook_form_alter : adds LinkedIn login to the login forms().
 */
function custom_linkedIn_form_alter(&$form, &$form_state, $form_id) {
    switch ($form_id) {
        //add login link to the login form
        case 'user_login':
            $form['login_with_linkedin'] = array(
                '#markup' => '<div class="linkedin login"><a href="/linkedin/login">'. t('login with LinkedIn') .'</a></div>',
                '#weight' => 100,
            );
            break;

        //Register using linkedin.
        case 'user_register_form':
            $form['register_with_linkedin'] = array(
                '#markup' => '<div class="linkedin register"><a href="/linkedin/register">'. t('register with LinkedIn') .'</a></div>',
            );
            break;

    }
    return $form;
}

/**
 * It is called the Linkedin api with ClientID
 * first the parameters are made
 * $arg: because it is called from different hook_menu we use arg for parameter
 */
function linkedin_get_token_request($arg){
    $parameter[] = "response_type=code";
    $parameter[] = "client_id=77xpw5r1ppmuby";
    $parameter[] = "redirect_uri=https://civil808.com/linkedin/" . $arg . "/finalize";
    $parameter[] = "scope=r_emailaddress r_basicprofile";
    $param = implode("&" , $parameter);
    $base_url = "https://www.linkedin.com/oauth/v2/authorization";
    $path = $base_url . "?" . $param;
    drupal_goto($path);
}

/**
 * It is called form LinkedIn Call Back
 * If everything is ok, It is backed with "code"
 * If there is an error, It is backed wih "error"
 */
function linked_in_login(){
    $code =  isset($_GET["code"]) && !empty($_GET["code"]) ? $_GET["code"] : "";
    $error = isset($_GET["error"]) && !empty($_GET["error"]) ? $_GET["error"] : "";
    if(($error === "user_cancelled_login" || $error === "user_cancelled_authorize")){
        drupal_set_message(t('Login with Linkedin is not completed'), 'status');
        drupal_goto("/user/login");
        die();
    }
    if(empty($code)){
        drupal_set_message(t('There was a problem with the configuration of LinkedIn on this website. Please try again later.'), 'error');
        drupal_goto("/user/login");
        die();
    }

    /*sending a request to get access token*/
    $curl = curl_init();
    curl_setopt_array($curl, array(
        CURLOPT_URL => "https://www.linkedin.com/oauth/v2/accessToken",
        CURLOPT_RETURNTRANSFER => true,
        CURLOPT_ENCODING => "",
        CURLOPT_MAXREDIRS => 10,
        CURLOPT_TIMEOUT => 30,
        CURLOPT_HTTP_VERSION => CURL_HTTP_VERSION_1_1,
        CURLOPT_CUSTOMREQUEST => "POST",
        CURLOPT_POSTFIELDS => "grant_type=authorization_code&code=" . $code . "&redirect_uri=https://civil808.com/linkedin/login/finalize&client_id=77xpw5r1ppmuby&client_secret=7iDuWEHv7yTOCgqx",
        CURLOPT_HTTPHEADER => array(
            "content-type: application/x-www-form-urlencoded"
        ),
    ));
    $response = curl_exec($curl);
    $err = curl_error($curl);
    curl_close($curl);
    if($err){
        drupal_set_message(t('There was a problem with the configuration of LinkedIn on this website. Please try again later.'), 'error');
        drupal_goto("/user/login");
        die();
    }
    $response = json_decode($response, true);
    if(isset($response["error"]) && !empty($response["error"])){
        drupal_set_message(t('There was a problem with the configuration of LinkedIn on this website. Please try again later.'), 'error');
        drupal_goto("/user/login");
        die();
    }

    /* If token is fetched correctly
     * sending request to fetch Email
     */
    $curl = curl_init();
    curl_setopt_array($curl, array(
//        CURLOPT_URL => "https://api.linkedin.com/v1/people/~:(id,public-profile-url,first-name,last-name,email-address,location,summary,num-connections,formatted-name,headline,industry,specialties,positions,picture-url,picture-urls::(original))?format=json",
        CURLOPT_URL => "https://api.linkedin.com/v1/people/~:(email-address)?format=json",
        CURLOPT_RETURNTRANSFER => true,
        CURLOPT_ENCODING => "",
        CURLOPT_MAXREDIRS => 10,
        CURLOPT_TIMEOUT => 30,
        CURLOPT_HTTP_VERSION => CURL_HTTP_VERSION_1_1,
        CURLOPT_CUSTOMREQUEST => "GET",
        CURLOPT_HTTPHEADER => array(
            "authorization: Bearer " . $response["access_token"],
            "cache-control: no-cache",
            "connection: Keep-Alive"
        ),
    ));
    $data = curl_exec($curl);
    $err = curl_error($curl);
    curl_close($curl);
    if($err){
        drupal_set_message(t('There was a problem with the configuration of LinkedIn on this website. Please try again later.'), 'error');
        drupal_goto("/user/login");
    }
    $email = json_decode($data, true);
    $email = $email["emailAddress"];

    /*if user has already logged in, just redirect */
    global $user;
    if($user->uid > 0) drupal_goto("/user/" . $user->uid);

    /*get the uid with this email for making the user login*/
    $uid = db_select("users" , "user")->fields("user" , array("uid"))->condition("mail" , $email)->execute()->fetch();
    if(empty($uid)){
        drupal_set_message(t('You are not join Civil808 or your account Email is not as same as your Linkedin Email'), 'error');
        drupal_goto("/user/login");
    }

    /*login user*/
    $user = user_load($uid->uid);
    user_login_finalize();

    db_merge("custom_linkedIn_token")
        ->key(array(
            "uid" => $user->uid
        ))
        ->fields(array(
            "token" => $response["access_token"],
            "location" => "login",
            "expire" => REQUEST_TIME + $response["expires_in"]
        ))->execute();

    drupal_goto("/user/" . $user->uid);
}

function linked_in_register(){
    $code =  isset($_GET["code"]) && !empty($_GET["code"]) ? $_GET["code"] : "";
    $error = isset($_GET["error"]) && !empty($_GET["error"]) ? $_GET["error"] : "";

    if(($error === "user_cancelled_login" || $error === "user_cancelled_authorize")){
        drupal_set_message(t('Login with Linkedin is not completed'), 'status');
        drupal_goto("/user/login");
    }
    if(empty($code)){
        drupal_set_message(t('There was a problem with the configuration of LinkedIn on this website. Please try again later.'), 'error');
        drupal_goto("/user/login");
    }

    $curl = curl_init();
    curl_setopt_array($curl, array(
        CURLOPT_URL => "https://www.linkedin.com/oauth/v2/accessToken",
        CURLOPT_RETURNTRANSFER => true,
        CURLOPT_ENCODING => "",
        CURLOPT_MAXREDIRS => 10,
        CURLOPT_TIMEOUT => 30,
        CURLOPT_HTTP_VERSION => CURL_HTTP_VERSION_1_1,
        CURLOPT_CUSTOMREQUEST => "POST",
        CURLOPT_POSTFIELDS => "grant_type=authorization_code&code=" . $code . "&redirect_uri=https://civil808.com/linkedin/register/finalize&client_id=77xpw5r1ppmuby&client_secret=7iDuWEHv7yTOCgqx",
        CURLOPT_HTTPHEADER => array(
            "content-type: application/x-www-form-urlencoded"
        ),
    ));
    $response = curl_exec($curl);
    $err = curl_error($curl);
    curl_close($curl);
    if($err){
        drupal_set_message(t('There was a problem with the configuration of LinkedIn on this website. Please try again later.'), 'error');
        drupal_goto("/user/login");
    }

    $response = json_decode($response, true);
    if(isset($response["error"]) && !empty($response["error"])){
        drupal_set_message(t('There was a problem with the configuration of LinkedIn on this website. Please try again later.'), 'error');
        drupal_goto("/user/login");
    }

    $curl = curl_init();
    curl_setopt_array($curl, array(
//        CURLOPT_URL => "https://api.linkedin.com/v1/people/~:(id,public-profile-url,first-name,last-name,email-address,location,summary,num-connections,formatted-name,headline,industry,specialties,positions,picture-url,picture-urls::(original))?format=json",
        CURLOPT_URL => "https://api.linkedin.com/v1/people/~:(first-name,last-name,formatted-name,email-address)?format=json",
        CURLOPT_RETURNTRANSFER => true,
        CURLOPT_ENCODING => "",
        CURLOPT_MAXREDIRS => 10,
        CURLOPT_TIMEOUT => 30,
        CURLOPT_HTTP_VERSION => CURL_HTTP_VERSION_1_1,
        CURLOPT_CUSTOMREQUEST => "GET",
        CURLOPT_HTTPHEADER => array(
            "authorization: Bearer " . $response["access_token"],
            "cache-control: no-cache",
            "connection: Keep-Alive"
        ),
    ));
    $data = curl_exec($curl);
    $err = curl_error($curl);
    curl_close($curl);
    if($err){
        drupal_set_message(t('There was a problem with the configuration of LinkedIn on this website. Please try again later.'), 'error');
        drupal_goto("/user/login");
    }
    $profile = json_decode($data, true);
    $full_name = $profile["formatted-name"];
    $email = $profile["emailAddress"];
    $username = explode("@" , $email);
    $username = $username[0];

    global $user;
    if($user->uid > 0) {
        drupal_goto("/user/" . $user->uid);
        die();
    }


    $uid = db_select("users" , "user")->fields("user" , array("uid"))->condition("mail" , $email)->execute()->fetch();
    if(!empty($uid)){
        $user = user_load($uid->uid);
        user_login_finalize();
        db_merge("custom_linkedIn_token")
            ->key(array(
                "uid" => $user->uid
            ))
            ->fields(array(
                "token" => $response["access_token"],
                "location" => "login",
                "expire" => REQUEST_TIME + $response["expires_in"]
            ))->execute();

        drupal_goto("/user/" . $user->uid);
        die();
    }
    do {
        $check_username = db_select("users", "user")->fields("user", array("uid"))->condition("name", $username)->execute()->fetch();
        if(!empty($check_username)) $username .= '1';
    }while(!empty($check_username));

    $pass = user_password();
    $new_user = array(
        'name' => $username,
        'password' => $pass,
        'mail' => $email,
        'status' => 1,
        'init' => $email,
        'roles' => array(
            DRUPAL_AUTHENTICATED_RID => 'authenticated user',
        ),
    );
    $user = user_save('', $new_user);
    $profile = profile2_create(array('type' => 'main', 'uid' => $user->uid));
    $profile->field_full_name['und'][0]['value'] = $full_name;
    profile2_save($profile);
    /*login user*/
    user_login_finalize();

    db_merge("custom_linkedIn_token")
        ->key(array(
            "uid" => $user->uid
        ))
        ->fields(array(
            "token" => $response["access_token"],
            "location" => "login",
            "expire" => REQUEST_TIME + $response["expires_in"]
        ))->execute();

    drupal_set_message(t('Note: choose a secret Password or You can not login again!'), 'warning');
    drupal_goto("user/" . $user->uid . "/edit#edit-account");
    die();
}

function linked_in_connect(){
    $code =  isset($_GET["code"]) && !empty($_GET["code"]) ? $_GET["code"] : "";
    $error = isset($_GET["error"]) && !empty($_GET["error"]) ? $_GET["error"] : "";
    if(($error === "user_cancelled_login" || $error === "user_cancelled_authorize")){
        drupal_set_message(t('Connect to Linkedin is not completed'), 'status');
        drupal_goto("/user");
        die();
    }
    if(empty($code)){
        drupal_set_message(t('There was a problem with the configuration of LinkedIn on this website. Please try again later.'), 'error');
        drupal_goto("/user");
        die();
    }

    /*sending a request to get access token*/
    $curl = curl_init();
    curl_setopt_array($curl, array(
        CURLOPT_URL => "https://www.linkedin.com/oauth/v2/accessToken",
        CURLOPT_RETURNTRANSFER => true,
        CURLOPT_ENCODING => "",
        CURLOPT_MAXREDIRS => 10,
        CURLOPT_TIMEOUT => 30,
        CURLOPT_HTTP_VERSION => CURL_HTTP_VERSION_1_1,
        CURLOPT_CUSTOMREQUEST => "POST",
        CURLOPT_POSTFIELDS => "grant_type=authorization_code&code=" . $code . "&redirect_uri=https://civil808.com/linkedin/connect/finalize&client_id=77xpw5r1ppmuby&client_secret=7iDuWEHv7yTOCgqx",
        CURLOPT_HTTPHEADER => array(
            "content-type: application/x-www-form-urlencoded"
        ),
    ));
    $response = curl_exec($curl);
    $err = curl_error($curl);
    curl_close($curl);
    if($err){
        drupal_set_message(t('There was a problem with the configuration of LinkedIn on this website. Please try again later.'), 'error');
        drupal_goto("/user");
        die();
    }
    $response = json_decode($response, true);
    if(isset($response["error"]) && !empty($response["error"])){
        drupal_set_message(t('There was a problem with the configuration of LinkedIn on this website. Please try again later.'), 'error');
        drupal_goto("/user");
        die();
    }

    global $user;
    db_merge("custom_linkedIn_token")
        ->key(array(
            "uid" => $user->uid
        ))
        ->fields(array(
            "token" => $response["access_token"],
            "location" => "login",
            "expire" => REQUEST_TIME + $response["expires_in"]
        ))->execute();

    drupal_goto("/user/" . $user->uid . "/linkedin");
    die();
}
function connect_access($uid){
    global $user;
    if($user->uid == $uid)
        return true;
    else
        return false;
}

function linked_in_profile($uid){
    $token = db_select("custom_linkedIn_token" , "token")
        ->fields("token" , array("token" , "expire"))
        ->condition("uid" , $uid)
        ->condition("expire" , REQUEST_TIME , ">")
        ->execute()->fetch();

    if(!empty($token)){
        global $user;
        if($user->uid == $uid &&
            $token->expire - REQUEST_TIME <= 86400
        ){
            return linkedin_get_token_request("connect");
        }

        $curl = curl_init();
        curl_setopt_array($curl, array(
            CURLOPT_URL => "https://api.linkedin.com/v1/people/~:(id,public-profile-url,first-name,last-name,email-address,location,summary,num-connections,formatted-name,headline,industry,specialties,positions,picture-url,picture-urls::(original))?format=json",
            CURLOPT_RETURNTRANSFER => true,
            CURLOPT_ENCODING => "",
            CURLOPT_MAXREDIRS => 10,
            CURLOPT_TIMEOUT => 30,
            CURLOPT_HTTP_VERSION => CURL_HTTP_VERSION_1_1,
            CURLOPT_CUSTOMREQUEST => "GET",
            CURLOPT_HTTPHEADER => array(
                "authorization: Bearer " . $token->token,
                "cache-control: no-cache",
                "connection: Keep-Alive"
            ),
        ));
        $data = curl_exec($curl);
        $err = curl_error($curl);
        curl_close($curl);
        if ($err) {
            drupal_set_message(t('There was a problem with the configuration of LinkedIn on this website. Please try again later.'), 'error');
            drupal_goto("/user/login");
        }
        $data = json_decode($data, true);

        $result = array();
        $result["full_name"] = $data["formattedName"];
        $result["headline"] = $data["headline"];
        $result["location"] = $data["location"]["name"];
        $result["Industry"] = $data["industry"];
        $result["summary"] = $data["summary"];
        $result["connections"] = $data["numConnections"];
        $result["profile"] = $data["publicProfileUrl"];
        $result["picture"] = !empty($data["pictureUrls"]["values"]) ? $data["pictureUrls"]["values"][0] : null;
        $result["positions"] = $data["positions"]["values"];

        return theme('custom_linkedIn_user_page', array('profile' => $result));
    }
    else{
        return previous_data($uid);
    }
}
function previous_data($uid){
    $account = user_load($uid);
    if(!isset($account->linkedin)){
        drupal_set_message(t('Your linkedIn profile is expired.'), 'error');
        drupal_goto("/user");
        die();
    }
    module_load_include("inc", "linkedin_profile", "linkedin_profile.pages");
    $access = linkedin_profile_display_access($account);
    if($access) return linkedin_profile_display($account);
    else return drupal_access_denied();
}

function has_linkedin_account($uid){
    $token = db_select("custom_linkedIn_token" , "token")
        ->fields("token" , array("token"))
        ->condition("uid" , $uid)
        ->condition("expire" , REQUEST_TIME , ">")
        ->execute()->fetch();

    if(!empty($token)) return true;

    $user = user_load($uid);
    if (isset($user->linkedin) && !empty($user->linkedin)) return true;

    return false;
}

function linkedin_token_expire(){
    global $user;
    if(arg(0) == 'user' && arg(1) == $user->uid){
        $token = db_select("custom_linkedIn_token" , "token")
            ->fields("token" , array("expire"))
            ->condition("uid" , $user->uid)
            ->execute()->fetch();
        if(empty($token)) return 0;
        return format_date($token->expire ,'short');
    }
    return false;
}