<?php

function question_resource_index(){
    /*
    return $domain;
    switch ($domain){
        case "all_questions" :
            return $domain;
            return all_questions($version , $page);
            break;
        case "my_questions" :
            break;
        case "following_questions" :
            break;
        case "my_experts_questions" :
            break;
        case "my_answered_questions" :
            break;
        default:
            return 0;
            break;
    }*/
}

function test(){
    return "ok";
}
